image: golang:1.16

stages:
  - build
  - test

.install_tempate: &install
  before_script:
    - export GOSUMDB=off
    - export GO111MODULE=on

build:
  <<: *install
  stage: build
  script:
    - go get -d ./...


unit-test-job: # This job runs in the test stage.
  <<: *install
  stage: test
  script:
    - go test ./... -v -covermode=atomic -coverpkg=./... -count=1 -race
    - echo "No test issues found."

lint-test-job: # This job also runs in the test stage.
  <<: *install
  stage: test
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
    - $GOPATH/bin/golangci-lint run ./...
    - echo "No lint issues found."

coverage-test-job: # This job runs in the test stage.
  <<: *install
  stage: test
  script:
    - go test ./... -covermode=atomic -coverpkg=./... -cover -coverprofile=c.out -count=1 -race
    - go tool cover -html=c.out -o coverage.html
    - go test ./... -v -bench=. > bench.log
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
    - $GOPATH/bin/golangci-lint run ./...
  artifacts:
    paths:
      - coverage.html
      - bench.log
