version: "3.5"
services:
    axul_contact:
        image: ncostamagna/axul_contact:${IMAGE_VERSION}
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000"
        environment:
            - DATABASE_HOST=axul-dev.cb1inrror0lv.us-east-1.rds.amazonaws.com
            - DATABASE_PORT=3306
            - DATABASE_NAME=axul_contact
            - DATABASE_USER=root
            - DATABASE_PASSWORD=Axul1989
            - DATABASE_DEBUG=true
            - DATABASE_MIGRATE=true
            - APP_PORT=5000
            - TOKEN=fb27698e-948a-4ece-8b56-0e2f11b1b34c

        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
        networks:
            - appnet
networks:
    appnet:
        driver: "bridge"
