version: '3.3'

services: 
    api:
        build: "."
        ports:
            - "5000"
        environment:
            - DATABASE_HOST=axul-dev.cb1inrror0lv.us-east-1.rds.amazonaws.com
            - DATABASE_PORT=3306
            - DATABASE_NAME=axul_contact
            - DATABASE_USER=root
            - DATABASE_PASSWORD=Axul1989
            - DATABASE_DEBUG=true
            - DATABASE_MIGRATE=true
            - APP_PORT=5000
            - TOKEN=fb27698e-948a-4ece-8b56-0e2f11b1b34c

        restart: "always"
        networks: 
            - "api.network"
        deploy:
            replicas: 1
            
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api
        ports: 
            - "8083:8081"
        networks: 
            - "api.network"
networks: 
    api.network: